# Generated by Django 2.0.5 on 2018-10-30 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_last_update_v',
            fields=[
                ('val_value', models.DecimalField(decimal_places=5, max_digits=15)),
                ('val_unit', models.CharField(max_length=5)),
                ('val_precision', models.PositiveSmallIntegerField(default=0)),
                ('val_format', models.PositiveSmallIntegerField(default=0)),
                ('val_sequence', models.PositiveSmallIntegerField(default=0)),
                ('val_description', models.CharField(blank=True, max_length=10, null=True)),
                ('sym_name', models.CharField(max_length=20)),
                ('sym_des', models.CharField(max_length=200, null=True)),
                ('cat_name', models.CharField(max_length=20)),
                ('cat_des', models.CharField(max_length=200, null=True)),
                ('pub_date', models.DateField()),
                ('pub_hour', models.TimeField()), 
            ],
            options={
                'db_table': 'all_last_update_v',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketupdate_model.Category')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_text', models.CharField(max_length=200, null=True)),
                ('pub_date', models.DateField()),
                ('pub_hour', models.TimeField()),
            ],
            options={
                'ordering': ['-pub_date', '-pub_hour'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=5, max_digits=15)),
                ('unit', models.CharField(choices=[('1', '%'), ('2', 'bp'), ('3', 'tick'), ('4', '')], default='4', max_length=5)),
                ('precision', models.PositiveSmallIntegerField(default=0)),
                ('val_format', models.PositiveSmallIntegerField(default=0)),
                ('val_sequence', models.PositiveSmallIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=10, null=True)),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketupdate_model.Symbol')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketupdate_model.Update'),
        ),
    ]
