# Generated by Django 2.0.5 on 2018-10-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketupdate_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all_last_update_v',
            options={'managed': True},
        ),
    ]
