# Generated by Django 2.0.5 on 2018-10-30 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketupdate_model', '0002_auto_20181030_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all_last_update_v',
            options={'managed': False},
        ),
    ]
