# Generated by Django 2.0.5 on 2018-11-05 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketupdate_model', '0003_auto_20181030_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketupdate_model.Update'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketupdate_model.Category'),
        ),
        migrations.AlterField(
            model_name='value',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketupdate_model.Symbol'),
        ),
        migrations.AlterField(
            model_name='value',
            name='unit',
            field=models.CharField(choices=[('1', '%'), ('2', 'bps'), ('3', 'ticks'), ('4', ''), ('5', '€'), ('6', 'pts')], default='4', max_length=5),
        ),
    ]
